server:
  port: 8083
spring:
  profiles:
    active: dev
---
server:
  port: 8084
spring:
  profiles: prod
---
#### 三个---隔离
server:
  port: 8085
spring:
  profiles: dev

person:
   name: zhangsan
   age: 23
   birth: 1997/2/3
   map: {k1:v1,k2:v2}
   list:
    - lisi
    - wangwu
   dog:
    name: xiaohua
    age: 2
